version: "3.7"

services:
  hoppscotch-backend:
    image: musketeers/hoppscotch:backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://hoppscotch:hoppscotch@182.184.67.82:9015/hoppscotch?connect_timeout=300
      - PORT=3170
    ports:
      - "3170:3170"

  hoppscotch-app:
    image: musketeers/hoppscotch:web
    depends_on:
      - hoppscotch-backend
    ports:
      - "3010:8080"

  hoppscotch-sh-admin:
    image: musketeers/hoppscotch:admin
    depends_on:
      - hoppscotch-backend
    ports:
      - "3100:8080"
